"""empty message

Revision ID: 035d67a3fcf7
Revises: 
Create Date: 2023-05-27 11:17:31.171618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '035d67a3fcf7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pay_roll',
    sa.Column('payroll_id', sa.Integer(), nullable=False),
    sa.Column('payrate', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('gross_pay', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('tax', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('net_pay', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('payroll_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pay_roll')
    # ### end Alembic commands ###
